export interface Game {
  id: string;
  title: string;
  description: string;
  authorId: string;
  authorName: string;
  thumbnailUrl?: string; // For the feed preview (video/image)
  code: string; // The HTML5/JS code generated by Gemini
  likes: number;
  createdAt: number;
  status: 'published' | 'draft';
}

export interface User {
  id: string;
  username: string;
  avatarUrl?: string;
  createdGames: string[]; // IDs of games created
  likedGames: string[]; // IDs of games liked
}

export interface GameGenerationRequest {
  prompt: string;
  difficulty?: 'easy' | 'medium' | 'hard';
  style?: string;
}
